name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: |
          yarn
      - name: Build
        run: |
          yarn build

      - uses: ./
        name: contributors-rounded-avatar
        with:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          repo: antvis/g2
          svgPath: examples/contributors-rounded-avatar.svg
          round: true
          includeBots: true

      - uses: ./
        name: contributors-squared-avatar
        with:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          repo: antvis/g2
          svgPath: examples/contributors-squared-avatar.svg
          round: false
          includeBots: true

      - uses: ./
        name: bots
        with:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          repo: antvis/g2
          svgPath: examples/bots.svg
          svgTemplate: >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              xmlns:xlink="http://www.w3.org/1999/xlink"
              version="1.1"
              width="{{ width }}"
              height="{{ botsHeight }}"
            >
              <style>.contributor-link { cursor: pointer; }</style>
              {{{ bots }}}
            </svg>


      - uses: ./
        name: collaborators
        with:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          repo: antvis/g2
          svgPath: examples/collaborators.svg
          svgTemplate: >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              xmlns:xlink="http://www.w3.org/1999/xlink"
              version="1.1"
              width="{{ width }}"
              height="{{ collaboratorsHeight }}"
            >
              <style>.contributor-link { cursor: pointer; }</style>
              {{{ collaborators }}}
            </svg>


      - uses: ./
        name: contributors-username
        with:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          repo: antvis/g2
          svgPath: examples/contributors-username.svg
          includeBots: true
          avatarSize: 64
          avatarMargin: 5
          userNameHeight: 19
          itemTemplate: >
            <g transform="translate({{ x }}, {{ y }})">
              <a xlink:href="{{{ url }}}" class="contributor-link" target="_blank" rel="nofollow sponsored" title="{{{ name }}}" id="{{{ name }}}">
                <image width="{{ width }}" height="{{ height }}" xlink:href="{{{ avatar }}}" />
                <text x="32" y="74" text-anchor="middle" alignment-baseline="middle" font-size="10">{{{ name }}}</text>
              </a>
            </g>


      - uses: ./
        name: contributors-bots
        with:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          repo: antvis/g2
          svgPath: examples/contributors-bots.svg
          includeBots: false
          avatarSize: 64
          avatarMargin: 5
          svgTemplate: >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              xmlns:xlink="http://www.w3.org/1999/xlink"
              version="1.1"
              width="{{ width }}"
              height="{{#sum}} {{ contributorsHeight }} +  {{ botsHeight }} + 32 + 32 {{/sum}}"
            >
              <style>.contributor-link { cursor: pointer; }</style>

              <text x="5" y="8" text-anchor="start" alignment-baseline="before-edge" font-size="24">Contributors</text>
              <g transform="translate(0, 32)">
                {{{ contributors }}}
              </g>

              <text x="5" y="{{#sum}} {{ contributorsHeight }} + 32 + 8 {{/sum}}" text-anchor="start" alignment-baseline="before-edge" font-size="24">Bots</text>
              <g transform="translate(0, {{#sum}} {{ contributorsHeight }} + 32 + 32 {{/sum}})">
                {{{ bots }}}
              </g>
            </svg>


      - uses: ./
        name: contributors-bots-collaborators
        with:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          repo: antvis/g2
          svgPath: examples/contributors-bots-collaborators.svg
          includeBots: false
          avatarSize: 64
          avatarMargin: 5
          svgTemplate: >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              xmlns:xlink="http://www.w3.org/1999/xlink"
              version="1.1"
              width="{{ width }}"
              height="{{#sum}} {{ contributorsHeight }} + {{ botsHeight }} + {{ collaboratorsHeight }} + 32 + 32 + 32 {{/sum}}"
            >
              <style>.contributor-link { cursor: pointer; }</style>

              <text x="5" y="5" text-anchor="start" alignment-baseline="before-edge" font-size="24">Contributors</text>
              <g transform="translate(0, 32)">
                {{{ contributors }}}
              </g>

              <text x="5" y="{{#sum}} {{ contributorsHeight }} + 32 + 8 {{/sum}}" text-anchor="start" alignment-baseline="before-edge" font-size="24">Bots</text>
              <g transform="translate(0, {{#sum}} {{ contributorsHeight }} + 32 + 32 {{/sum}})">
                {{{ bots }}}
              </g>

              <text x="5" y="{{#sum}} {{ contributorsHeight }} + {{ botsHeight }} + 32 + 32 + 8 {{/sum}}" text-anchor="start" alignment-baseline="before-edge" font-size="24">Collaborators</text>
              <g transform="translate(0, {{#sum}} {{ contributorsHeight }} + {{ botsHeight }} + 32 + 32 + 32 {{/sum}})">
                {{{ collaborators }}}
              </g>
            </svg>

